# Generated by Django 5.1.4 on 2025-04-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='available_time',
        ),
        migrations.AddField(
            model_name='pin',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
