# Generated by Django 5.1.4 on 2025-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_remove_pin_end_time_remove_pin_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='available_time',
        ),
        migrations.AddField(
            model_name='pin',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
