# Generated by Django 5.1.4 on 2025-02-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='child_ages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='num_children',
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_standing',
            field=models.CharField(blank=True, choices=[('', 'NOT SPECIFIED'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('DR', 'Doctorate')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
