# Generated by Django 5.1.4 on 2025-03-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_remove_profile_child_ages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uID',
        ),
    ]
