# Generated by Django 5.1.4 on 2025-03-17 11:55

import userProfile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_remove_profile_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_type', models.CharField(blank=True, choices=[('NS', 'Ask me to find out'), ('OP', "I'm open to anything"), ('FL', "Family Life: Parks, kid's places, museums, pools"), ('SO', 'Socials: Dinners, brunches, parties, board games'), ('CI', 'Chill Indoors: Reading, Netflix and chill, games, movies'), ('AI', 'Active Indoors: Pilates, weight-lifting, dancing, martial arts'), ('CO', 'Chill Outdoors: Strolling, site-seeing, gardening, yoga'), ('AO', 'Active Outdoors: Hiking, camping, biking, mud-runners')], default='NS', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='userProfile.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_standing',
            field=models.CharField(blank=True, choices=[('NS', 'NOT SPECIFIED'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('DR', 'Doctorate')], default='NS', max_length=2),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pictures/jolly_rancher.jpg', upload_to=userProfile.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(related_name='participants', to='userProfile.hobby'),
        ),
    ]
