# Generated by Django 5.1.4 on 2025-03-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_hobby_profile_friends_alter_profile_class_standing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_type',
            field=models.CharField(blank=True, choices=[('NS', 'Ask me to find out'), ('OP', "I'm open to anything"), ('FL', "Family Life: Parks, kid's places, museums, pools"), ('SO', 'Socials: Dinners, brunches, parties, board games'), ('CI', 'Chill Indoors: Reading, Netflix and chill, games, movies'), ('AI', 'Active Indoors: Pilates, weight-lifting, dancing, martial arts'), ('CO', 'Chill Outdoors: Strolling, site-seeing, gardening, yoga'), ('AO', 'Active Outdoors: Hiking, camping, biking, mud-runners')], default='N', max_length=2),
        ),
    ]
