# Generated by Django 5.1.4 on 2025-03-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_alter_hobby_hobby_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_type',
            field=models.CharField(choices=[('NS', 'Ask me to find out'), ('OP', "I'm open to anything"), ('FL', "Family Life: Parks, kid's places, museums, pools"), ('SO', 'Socials: Dinners, brunches, parties, board games'), ('CI', 'Chill Indoors: Reading, Netflix and chill, games, movies'), ('AI', 'Active Indoors: Pilates, weight-lifting, dancing, martial arts'), ('CO', 'Chill Outdoors: Strolling, site-seeing, gardening, yoga'), ('AO', 'Active Outdoors: Hiking, camping, biking, mud-runners')], default='NS', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_standing',
            field=models.CharField(choices=[('NS', 'NOT SPECIFIED'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('DR', 'Doctorate')], default='NS', max_length=2),
        ),
    ]
