# Generated by Django 5.1.4 on 2025-04-02 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_alter_hobby_hobby_type_alter_profile_class_standing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_check',
            field=models.CharField(choices=[('CL', 'Cleared'), ('IP', 'In progress'), ('NO', 'Not started')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_standing',
            field=models.CharField(choices=[('NS', 'Not specified'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('DR', 'Doctorate')], default='NS', max_length=2),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AC', 'accepted'), ('RE', 'declined'), ('IG', 'ignored'), ('BL', 'blocked'), ('Pe', 'pending')], default='Pe', max_length=2)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
