# Generated by Django 5.1.3 on 2025-04-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('AC', 'accepted'), ('DE', 'declined'), ('IG', 'ignored'), ('BL', 'blocked'), ('Pe', 'pending')], default='Pe', max_length=2),
        ),
    ]
